// <auto-generated />
using System;
using KauRestaurant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KauRestaurant.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250313181531_AddMenuMealsAndReviews")]
    partial class AddMenuMealsAndReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KauRestaurant.Areas.Identity.Data.KauRestaurantUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KauRestaurant.Models.Meal", b =>
                {
                    b.Property<int>("MealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MealID"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("Carbs")
                        .HasColumnType("int");

                    b.Property<int>("Fat")
                        .HasColumnType("int");

                    b.Property<string>("MealCategory")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MealName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.HasKey("MealID");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            MealID = 1,
                            Calories = 250,
                            Carbs = 45,
                            Fat = 10,
                            MealCategory = "الإفطار",
                            MealName = "فطائر بالجبن",
                            MealType = "الطبق الرئيسي",
                            Protein = 8
                        },
                        new
                        {
                            MealID = 2,
                            Calories = 185,
                            Carbs = 2,
                            Fat = 14,
                            MealCategory = "الإفطار",
                            MealName = "بيض مقلي",
                            MealType = "الطبق الرئيسي",
                            Protein = 12
                        },
                        new
                        {
                            MealID = 3,
                            Calories = 220,
                            Carbs = 35,
                            Fat = 5,
                            MealCategory = "الإفطار",
                            MealName = "فول مدمس",
                            MealType = "طبق جانبي",
                            Protein = 15
                        },
                        new
                        {
                            MealID = 4,
                            Calories = 180,
                            Carbs = 25,
                            Fat = 9,
                            MealCategory = "الإفطار",
                            MealName = "حمص بالطحينة",
                            MealType = "طبق جانبي",
                            Protein = 8
                        },
                        new
                        {
                            MealID = 5,
                            Calories = 5,
                            Carbs = 1,
                            Fat = 0,
                            MealCategory = "الإفطار",
                            MealName = "شاي عربي",
                            MealType = "مشروب",
                            Protein = 0
                        },
                        new
                        {
                            MealID = 6,
                            Calories = 120,
                            Carbs = 28,
                            Fat = 0,
                            MealCategory = "الإفطار",
                            MealName = "عصير برتقال طازج",
                            MealType = "مشروب",
                            Protein = 1
                        },
                        new
                        {
                            MealID = 7,
                            Calories = 450,
                            Carbs = 55,
                            Fat = 15,
                            MealCategory = "الغداء",
                            MealName = "كبسة لحم",
                            MealType = "الطبق الرئيسي",
                            Protein = 28
                        },
                        new
                        {
                            MealID = 8,
                            Calories = 350,
                            Carbs = 0,
                            Fat = 20,
                            MealCategory = "الغداء",
                            MealName = "دجاج مشوي",
                            MealType = "الطبق الرئيسي",
                            Protein = 30
                        },
                        new
                        {
                            MealID = 9,
                            Calories = 65,
                            Carbs = 12,
                            Fat = 2,
                            MealCategory = "الغداء",
                            MealName = "سلطة خضراء",
                            MealType = "طبق جانبي",
                            Protein = 3
                        },
                        new
                        {
                            MealID = 10,
                            Calories = 180,
                            Carbs = 30,
                            Fat = 5,
                            MealCategory = "الغداء",
                            MealName = "شوربة عدس",
                            MealType = "طبق جانبي",
                            Protein = 10
                        },
                        new
                        {
                            MealID = 11,
                            Calories = 350,
                            Carbs = 52,
                            Fat = 15,
                            MealCategory = "الغداء",
                            MealName = "أم علي",
                            MealType = "حلوى",
                            Protein = 8
                        },
                        new
                        {
                            MealID = 12,
                            Calories = 90,
                            Carbs = 12,
                            Fat = 5,
                            MealCategory = "الغداء",
                            MealName = "لبن عيران",
                            MealType = "مشروب",
                            Protein = 8
                        },
                        new
                        {
                            MealID = 13,
                            Calories = 380,
                            Carbs = 40,
                            Fat = 20,
                            MealCategory = "العشاء",
                            MealName = "شاورما دجاج",
                            MealType = "الطبق الرئيسي",
                            Protein = 25
                        },
                        new
                        {
                            MealID = 14,
                            Calories = 420,
                            Carbs = 35,
                            Fat = 25,
                            MealCategory = "العشاء",
                            MealName = "برجر لحم",
                            MealType = "الطبق الرئيسي",
                            Protein = 28
                        },
                        new
                        {
                            MealID = 15,
                            Calories = 365,
                            Carbs = 48,
                            Fat = 18,
                            MealCategory = "العشاء",
                            MealName = "بطاطس مقلية",
                            MealType = "طبق جانبي",
                            Protein = 4
                        },
                        new
                        {
                            MealID = 16,
                            Calories = 150,
                            Carbs = 15,
                            Fat = 10,
                            MealCategory = "العشاء",
                            MealName = "سلطة سيزر",
                            MealType = "طبق جانبي",
                            Protein = 8
                        },
                        new
                        {
                            MealID = 17,
                            Calories = 400,
                            Carbs = 58,
                            Fat = 20,
                            MealCategory = "العشاء",
                            MealName = "كنافة",
                            MealType = "حلوى",
                            Protein = 6
                        },
                        new
                        {
                            MealID = 18,
                            Calories = 80,
                            Carbs = 20,
                            Fat = 0,
                            MealCategory = "العشاء",
                            MealName = "عصير ليمون بالنعناع",
                            MealType = "مشروب",
                            Protein = 1
                        },
                        new
                        {
                            MealID = 19,
                            Calories = 120,
                            Carbs = 28,
                            Fat = 0,
                            MealCategory = "الإفطار",
                            MealName = "عصير برتقال طازج",
                            MealType = "مشروب",
                            Protein = 1
                        },
                        new
                        {
                            MealID = 20,
                            Calories = 420,
                            Carbs = 63,
                            Fat = 22,
                            MealCategory = "العشاء",
                            MealName = "كعكة الشوكولاتة",
                            MealType = "حلوى",
                            Protein = 5
                        });
                });

            modelBuilder.Entity("KauRestaurant.Models.Menu", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuID"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MenuID");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            Day = "الأحد"
                        },
                        new
                        {
                            MenuID = 2,
                            Day = "الإثنين"
                        },
                        new
                        {
                            MenuID = 3,
                            Day = "الثلاثاء"
                        },
                        new
                        {
                            MenuID = 4,
                            Day = "الأربعاء"
                        },
                        new
                        {
                            MenuID = 5,
                            Day = "الخميس"
                        });
                });

            modelBuilder.Entity("KauRestaurant.Models.MenuMeal", b =>
                {
                    b.Property<int>("MenuMealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuMealID"));

                    b.Property<int>("MealID")
                        .HasColumnType("int");

                    b.Property<int>("MenuID")
                        .HasColumnType("int");

                    b.HasKey("MenuMealID");

                    b.HasIndex("MealID");

                    b.HasIndex("MenuID");

                    b.ToTable("MenuMeals", (string)null);

                    b.HasData(
                        new
                        {
                            MenuMealID = 1,
                            MealID = 1,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 2,
                            MealID = 2,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 3,
                            MealID = 3,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 4,
                            MealID = 4,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 5,
                            MealID = 5,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 6,
                            MealID = 6,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 7,
                            MealID = 7,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 8,
                            MealID = 8,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 9,
                            MealID = 9,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 10,
                            MealID = 10,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 11,
                            MealID = 11,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 12,
                            MealID = 12,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 13,
                            MealID = 13,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 14,
                            MealID = 14,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 15,
                            MealID = 15,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 16,
                            MealID = 16,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 17,
                            MealID = 17,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 18,
                            MealID = 18,
                            MenuID = 1
                        },
                        new
                        {
                            MenuMealID = 19,
                            MealID = 19,
                            MenuID = 2
                        },
                        new
                        {
                            MenuMealID = 20,
                            MealID = 1,
                            MenuID = 2
                        },
                        new
                        {
                            MenuMealID = 21,
                            MealID = 7,
                            MenuID = 2
                        },
                        new
                        {
                            MenuMealID = 22,
                            MealID = 13,
                            MenuID = 2
                        },
                        new
                        {
                            MenuMealID = 23,
                            MealID = 20,
                            MenuID = 3
                        },
                        new
                        {
                            MenuMealID = 24,
                            MealID = 2,
                            MenuID = 3
                        },
                        new
                        {
                            MenuMealID = 25,
                            MealID = 8,
                            MenuID = 3
                        },
                        new
                        {
                            MenuMealID = 26,
                            MealID = 14,
                            MenuID = 3
                        },
                        new
                        {
                            MenuMealID = 27,
                            MealID = 3,
                            MenuID = 4
                        },
                        new
                        {
                            MenuMealID = 28,
                            MealID = 9,
                            MenuID = 4
                        },
                        new
                        {
                            MenuMealID = 29,
                            MealID = 15,
                            MenuID = 4
                        },
                        new
                        {
                            MenuMealID = 30,
                            MealID = 19,
                            MenuID = 4
                        },
                        new
                        {
                            MenuMealID = 31,
                            MealID = 4,
                            MenuID = 5
                        },
                        new
                        {
                            MenuMealID = 32,
                            MealID = 10,
                            MenuID = 5
                        },
                        new
                        {
                            MenuMealID = 33,
                            MealID = 16,
                            MenuID = 5
                        },
                        new
                        {
                            MenuMealID = 34,
                            MealID = 20,
                            MenuID = 5
                        });
                });

            modelBuilder.Entity("KauRestaurant.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("BreakfastTicketsCount")
                        .HasColumnType("int");

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DinnerTicketsCount")
                        .HasColumnType("int");

                    b.Property<int>("LunchTicketsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("TotalPaid")
                        .HasColumnType("real");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KauRestaurant.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewID"));

                    b.Property<string>("CustomerID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MealID")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ReviewID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("MealID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("YourNamespace.Models.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<bool>("IsRedeemed")
                        .HasColumnType("bit");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<string>("QRCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TicketID");

                    b.HasIndex("OrderID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("KauRestaurant.Models.MenuMeal", b =>
                {
                    b.HasOne("KauRestaurant.Models.Meal", "Meal")
                        .WithMany("MenuMeals")
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KauRestaurant.Models.Menu", "Menu")
                        .WithMany("MenuMeals")
                        .HasForeignKey("MenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meal");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("KauRestaurant.Models.Order", b =>
                {
                    b.HasOne("KauRestaurant.Areas.Identity.Data.KauRestaurantUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("KauRestaurant.Models.Review", b =>
                {
                    b.HasOne("KauRestaurant.Areas.Identity.Data.KauRestaurantUser", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KauRestaurant.Models.Meal", "Meal")
                        .WithMany("Reviews")
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("KauRestaurant.Areas.Identity.Data.KauRestaurantUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("KauRestaurant.Areas.Identity.Data.KauRestaurantUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KauRestaurant.Areas.Identity.Data.KauRestaurantUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("KauRestaurant.Areas.Identity.Data.KauRestaurantUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourNamespace.Models.Ticket", b =>
                {
                    b.HasOne("KauRestaurant.Models.Order", "Order")
                        .WithMany("Tickets")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("KauRestaurant.Models.Meal", b =>
                {
                    b.Navigation("MenuMeals");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("KauRestaurant.Models.Menu", b =>
                {
                    b.Navigation("MenuMeals");
                });

            modelBuilder.Entity("KauRestaurant.Models.Order", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
